name: Fuzz

on:
  push:
    branches: [ "ttchef" ]

jobs:
  fuzzing:
    name: Fuzz
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang

    - name: Fuzz PNG
      run: |
        cd tests
        make fuzz-png

    - name: Fuzz TTF
      run: |
        cd tests
        make fuzz-ttf

    - name: Fuzz WAV
      run: |
        cd tests
        make fuzz-wav

    - name: Fuzz MAP
      run: |
        cd tests
        make fuzz-map
